### ISSUE TITLE
Can't find Citizens.jar

### ISSUE THREAD

**Issue by TheCactusMonkey** [LichtHund/CitizensCMD#1]
### Describe the bug
I get a error message in the console while lanuching my 1.13 spigot server. When it's enabling CitizensCMD and then trying to find Citizens but it fails which leads to that CitizensCMD gets disabled.

### To Reproduce
1. Start the server
2. Wait for it to load
3. CitizensCMD is getting enabled
4. Error from Console:
```
[18:51:55 INFO]: [CitizensCMD] Enabling CitizensCMD v2.1
[18:51:55 INFO]: [CitizensCMD] Citizens is needed for this plugin to work!
[18:51:55 INFO]: [CitizensCMD] Citizens.jar is not installed on the server!
[18:51:55 INFO]: [CitizensCMD] Disabling CitizensCMD...
[18:51:55 INFO]: [CitizensCMD] Disabling CitizensCMD v2.1
[18:51:55 ERROR]: Error occurred while disabling CitizensCMD v2.1 (Is it up to d
ate?)
java.lang.NullPointerException: null
        at me.mattmoreira.citizenscmd.CitizensCMD.onDisable(CitizensCMD.java:215
) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[s
pigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoade
r.java:363) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManag
er.java:422) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at me.mattmoreira.citizenscmd.CitizensCMD.onEnable(CitizensCMD.java:81)
[CitizensCMD.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [sp
igot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:339) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:403) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.
java:426) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer
.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:
562) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java
:524) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:
423) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.ja
va:288) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.jav
a:686) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

### Expected behavior
The plugin should load in with Citizens but it doesnt, it just gets disabled. So I thought there were some problems with the Citizens.jar file but i downloaded the latest one, but I got the same error and CitizensCMD got disabled once more.

### Screenshots
All my plugins (may help, but I don't think so myself):
![image](https://user-images.githubusercontent.com/30912172/44678979-05630280-aa3a-11e8-8902-75ddbd2fc2ff.png)

### Versions
 - Citizens version:   **citizens-2.0.24-SNAPSHOT.jar**
 - Spigot version:   **spigot-1.13-R0.1-SNAPSHOT-b1851.jar**
 - CitizensCMD version:   **CitizensCMD v2.1**
 - Java version:   **Java 8 (build: 1.8.0_181-b13)**

### Additional context
I thought that it needed the Citizens file to be called exactly Citizens.jar but that doesn't make any difference. I have tried both **Citizens.jar** & **citizens.jar**

**Comment by LichtHund** [comment]
Is Citizens enabling on startup?
Or do you get an error message from Citizens before you get the message from CitizensCMD?

**Comment by TheCactusMonkey** [comment]
I didn't think about that, thats why it's not working. The version I'm using right now is probably for 1.13.1 and I'm still at 1.13
```
[20:40:10 INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1567)
[20:40:10 ERROR]: [Citizens] Missing preferred location bundle.
[20:40:10 ERROR]: [Citizens] v2.0.24-SNAPSHOT (build 1567) is not compatible with
Minecraft v1_13_R1 - try upgrading or downgrading Citizens. Disabling.
[20:40:10 INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1567)
```

> This Issue can probably be closed now.

**Comment by LichtHund** [comment]
Yeah, if Citizens doesn't load CitizensCMD won't either.

**Comment by TheCactusMonkey** [comment]
I'll look into Citizens then!
Thanks :)
