### ISSUE TITLE
bug console load

### ISSUE THREAD

**Issue by Xeraccoon** [LichtHund/CitizensCMD#26]
[22:18:15] [Server thread/ERROR]: Error occurred while disabling CitizensCMD v2.3.2 (Is it up to date?)

java.lang.NullPointerException: null

	at me.mattstudios.citizenscmd.files.CooldownHandler.createBasics(CooldownHandler.java:67) ~[CitizensCMD.jar:?]

	at me.mattstudios.citizenscmd.files.CooldownHandler.saveToFile(CooldownHandler.java:108) ~[CitizensCMD.jar:?]

	at me.mattstudios.citizenscmd.CitizensCMD.onDisable(CitizensCMD.java:220) ~[CitizensCMD.jar:?]

	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]

	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]

	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]

	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:429) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]

	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:392) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]

	at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:679) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]

	at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:681) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]

	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:845) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by LichtHund** [comment]
Is this on load?
Which Citizens version are you using?

**Comment by Xeraccoon** [comment]
yes , 1.14.3

**Comment by LichtHund** [comment]
I mean Citizens version, not spigot.

**Comment by Xeraccoon** [comment]
the last, but i not have the bug today, but he can comeback

**Comment by LichtHund** [comment]
Should be fixed.
