### ISSUE TITLE
Unexpected network call

### ISSUE THREAD

**Issue by SlimeDog** [LichtHund/CitizensCMD#27]
**Describe the bug**
Update-check network call is made every hour, even though configuration is set to disable it.

**To Reproduce**
1. Configure network to disallow outbound calls.
2. Configure CitizensCMD to disable update checks.
3. Start server.
4. Observe errors in console/log. 

**Expected behavior**
CitizensCMD should not make outbound network calls.

**Screenshots**

**Versions (please complete the following information):**
 - Citizens 2.0.25-SNAPSHOT (build 1719)
 - Spigot 1.13.2 final = git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 - CitizensCMD 2.3.2
- Java 11.0.3 on up-to-date CentOS platform

**Additional context**
```
# Citizens CMD Plugin by Mateus Moreira
# @LichtHund
# Version 2.3.2
# Wiki: https://github.com/ipsk/CitizensCMD/wiki
# GitHub: https://github.com/ipsk/CitizensCMD
# Spigot: https://www.spigotmc.org/resources/citizens-cmd.30224/

#
# Enables Checking for update.
check-updates: false
```
```
[08:20:58 WARN]: java.io.IOException: Connect failed
[08:20:58 WARN]:        at me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor$LoggingSelector.select(ProxySelectorInterceptor.java:59)
[08:20:58 WARN]:        at com.github.games647.lagmonitor.listener.BlockingConnectionSelector.select(BlockingConnectionSelector.java:33)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1175)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1065)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1063)
[08:20:58 WARN]:        at java.base/java.security.AccessController.doPrivileged(Native Method)
[08:20:58 WARN]:        at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:793)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1062)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1501)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1499)
[08:20:58 WARN]:        at java.base/java.security.AccessController.doPrivileged(Native Method)
[08:20:58 WARN]:        at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:793)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[08:20:58 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
[08:20:58 WARN]:        at me.mattstudios.citizenscmd.updater.SpigotUpdater.checkForUpdates(SpigotUpdater.java:65)
[08:20:58 WARN]:        at me.mattstudios.citizenscmd.schedulers.UpdateScheduler.run(UpdateScheduler.java:40)
[08:20:58 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[08:20:58 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[08:20:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08:20:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08:20:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by LichtHund** [comment]
Thanks for letting me know, I'll be updating the update checker soon.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by LichtHund** [comment]
Should be fixed.
