### ISSUE TITLE
Unhandled exception during reloading

### ISSUE THREAD

**Issue by Vlader97** [LichtHund/CitizensCMD#29]
**Describe the bug**
It is easier for me to edit files than to use commands. But if I make a mistake in saves.yml and then use /npcmd reload. I'll get this stacktrace.
```
[19:10:18] [Server thread/INFO]: [CitizensCMD] Using English messages!
[19:10:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'npcmd' in plugin CitizensCMD v2.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.3.jar:git-Paper-130]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-130]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-130]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-130]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Cannot translate null text
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.3.jar:git-Paper-130]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[patched_1.14.3.jar:git-Paper-130]
	at me.mattstudios.citizenscmd.utility.Util.color(Util.java:130) ~[?:?]
	at me.mattstudios.citizenscmd.files.LangHandler.getMessage(LangHandler.java:302) ~[?:?]
	at me.mattstudios.citizenscmd.commands.CMDReload.execute(CMDReload.java:69) ~[?:?]
	at me.mattstudios.citizenscmd.commands.base.CommandHandler.onCommand(CommandHandler.java:109) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.3.jar:git-Paper-130]
	... 17 more
```
**To Reproduce**
1. Go to data/saves.yml
2. Make a mistake in this file.
3. Use /npcmd reload

**Expected behavior**
I would expect a message that there is an error in the file.
Ideally, the message shows where the problem is.

**Versions:**
 - Citizens version: 2.0.25-b1719
 - Paper version: 1.14.3 b130
 - CitizensCMD version: 2.3.2
 - Java version: 1.8.0_151

**Comment by jeannen** [comment]
Same probleme here

**Comment by LichtHund** [comment]
Fixed.
