### ISSUE TITLE
error: Citizens missing

### ISSUE THREAD

**Issue by RenaudRl** [LichtHund/CitizensCMD#3]
Hello, i have a problem , i test different version of citizens 1.13 and the plugin say : 

[19:24:38] [Server thread/INFO]: [0;37;1m[[0;36;22mCitizens[0;31;1mCMD[0;37;1m][m [0;31;1mCitizens [0;37;22mis needed for this plugin to work![m
[19:24:38] [Server thread/INFO]: [0;37;1m[[0;36;22mCitizens[0;31;1mCMD[0;37;1m][m [0;31;1mCitizens.jar [0;37;22mis not installed on the server![m
[19:24:38] [Server thread/INFO]: [0;37;1m[[0;36;22mCitizens[0;31;1mCMD[0;37;1m][m [0;31;1mDisabling CitizensCMD...[m
[19:24:38] [Server thread/INFO]: [CitizensCMD] Disabling CitizensCMD v2.1
[19:24:38] [Server thread/ERROR]: Error occurred while disabling CitizensCMD v2.1 (Is it up to date?)
java.lang.NullPointerException: null
	at me.mattmoreira.citizenscmd.CitizensCMD.onDisable(CitizensCMD.java:215) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at me.mattmoreira.citizenscmd.CitizensCMD.onEnable(CitizensCMD.java:81) [CitizensCMD.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by LichtHund** [comment]
That is not a CitizensCMD problem, it is simply saying that Citizens is not being enabled, your Citizens is not working.
You may be using the wrong version of it.
