### ISSUE TITLE
CommandException: Unhandled exception during tab completion for command '/npcmd remove left

### ISSUE THREAD

**Issue by mibby** [LichtHund/CitizensCMD#33]
Paper dev 175 (Spigot 1.14.4)
Citizens2 dev 1744
CitizensCMD v2.3.2

```
[11:14:55] [Server thread/ERROR]: Exception when mibby attempted to tab complete npcmd remove left 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/npcmd remove left ' in plugin CitizensCMD v2.3.2
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.tabCompleteCommand(CraftServer.java:1716) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.tabComplete(CraftServer.java:1688) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[patched_1.14.4.jar:git-Paper-175]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.14.4.jar:git-Paper-175]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.14.4.jar:git-Paper-175]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.PlayerConnection.lambda$a$3(PlayerConnection.java:563) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923) ~[patched_1.14.4.jar:git-Paper-175]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at me.mattstudios.citizenscmd.files.DataHandler.getCompleteCommandsNumbers(DataHandler.java:364) ~[?:?]
	at me.mattstudios.citizenscmd.utility.Util.getTabCompleteArgs(Util.java:169) ~[?:?]
	at me.mattstudios.citizenscmd.commands.base.CommandHandler.getCommandNames(CommandHandler.java:216) ~[?:?]
	at me.mattstudios.citizenscmd.commands.base.CommandHandler.onTabComplete(CommandHandler.java:177) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[patched_1.14.4.jar:git-Paper-175]
	... 19 more
```

**Comment by LichtHund** [comment]
Fixed.
