### ISSUE TITLE
on boot, plug crashes

### ISSUE THREAD

**Issue by CaszGamerMD** [LichtHund/CitizensCMD#43]
```
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyInputStreamToFile(Ljava/io/InputStream;Ljava/io/File;)V
	at me.mattstudios.citizenscmd.utility.YamlUtils.copyDefaults(YamlUtils.java:25) ~[?:?]
	at me.mattstudios.citizenscmd.CitizensCMD.onEnable(CitizensCMD.java:89) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by LichtHund** [comment]
How about some context? Plugin version, Citizens version, Spigot version?

**Comment by CaszGamerMD** [comment]
Sorry, forgot to add that

Paper-1.15.2-304
Citizens 2.0.26-snap build 1959
CitizenCMD 2.4

**Comment by CaszGamerMD** [comment]
it has something connected with the plugin, dropedit2
it fails to load CCMD every boot, but if i unload DropEdit2, then load CCMD, then reload DropEdit2; it works fine...

**Comment by LichtHund** [comment]
Fixed, had to relocate the lib. It's caused by another plugin using the same lib but an outdated version of it.
