### ISSUE TITLE
Can't use on 1.16.2 server

### ISSUE THREAD

**Issue by SleepyAsh0191** [LichtHund/CitizensCMD#47]
**Describe the bug**
Can't use on 1.16.2 server

**To Reproduce**
Type /npcmd or interact with npc

**Expected behavior**
appeared an interal error occorred while attempting to perforn this command

**Versions (please complete the following information):**
 - Citizens version
Citizens-2.0.27-b2100
 - Spigot version
1.16.2
 - CitizensCMD version
2.5
- Java version 
Java 14

**Additional context**
Error text:
`[19:42:38 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'npcmd' in plugin CitizensCMD v2.5 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.2.jar:git-Paper-147]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.2.jar:git-Paper-147]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1907) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1718) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-147]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-147]
        at java.lang.Thread.run(Thread.java:832) [?:?]`

**Comment by SleepyAsh0191** [comment]
my fault because CitizensCMD is loaded before Citizens.
